// frontend-vue/src/components/main/Sidebar.vue
<template>
  <aside class="w-56 bg-white border-r border-gray-200 flex-shrink-0 overflow-y-auto">
    <nav class="py-4">
      <template v-for="node in menuTree" :key="node.menuId">
        <!-- 최상위: URL 있으면 링크, 없으면 그룹 -->
        <div v-if="!node.children || node.children.length === 0" class="mb-2">
          <router-link v-if="node.menuUrl" :to="node.menuUrl" :class="linkClass(node.menuUrl)">
            {{ node.menuNm }}
          </router-link>
        </div>
        <div v-else class="mb-1">
          <button
            type="button"
            @click="toggleGroup(node.menuId)"
            class="w-full flex items-center justify-between px-4 py-2 text-sm font-semibold text-gray-500 uppercase tracking-wider hover:bg-gray-50 transition-colors"
          >
            <span>{{ node.menuNm }}</span>
            <span class="text-xs text-gray-400">{{ openGroups.has(node.menuId) ? '▾' : '▸' }}</span>
          </button>
          <template v-if="openGroups.has(node.menuId)">
            <menu-tree-item
              v-for="child in node.children"
              :key="child.menuId"
              :node="child"
              :depth="2"
              :open-groups="openGroups"
              :current-path="route.path"
              @toggle="toggleGroup"
            />
          </template>
        </div>
      </template>
    </nav>
  </aside>
</template>

<script setup>
import { ref, computed, watch, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { useMenuStore } from '../../stores/menu'
import MenuTreeItem from './MenuTreeItem.vue'

const route = useRoute()
const menuStore = useMenuStore()

const menuTree = computed(() => menuStore.menuTree)

const openGroups = ref(new Set())

function findGroupForPath(pathname, nodes) {
  for (const node of nodes) {
    if (node.menuUrl === pathname) return node.menuId
    if (node.children && node.children.length > 0) {
      for (const child of node.children) {
        if (child.menuUrl === pathname) return node.menuId
        if (child.children && child.children.length > 0) {
          const found = findGroupForPath(pathname, [child])
          if (found) {
            openGroups.value = new Set([...openGroups.value, node.menuId])
            return found
          }
        }
      }
    }
  }
  return null
}

const initGroup = () => {
  const activeGroup = findGroupForPath(route.path, menuTree.value)
  if (activeGroup && !openGroups.value.has(activeGroup)) {
    openGroups.value = new Set([...openGroups.value, activeGroup])
  }
}

watch(() => route.path, initGroup)
watch(menuTree, initGroup)

onMounted(() => {
  if (menuTree.value.length > 0) {
    initGroup()
  }
})

const toggleGroup = (groupId) => {
  const next = new Set(openGroups.value)
  if (next.has(groupId)) next.delete(groupId)
  else next.add(groupId)
  openGroups.value = next
}

const linkClass = (to) => {
  const isActive = route.path === to
  return `block px-4 py-2 text-sm transition-colors ${
    isActive
      ? 'text-[#2563EB] bg-blue-50 font-medium'
      : 'text-gray-600 hover:bg-gray-50 hover:text-gray-800'
  }`
}
</script>

// frontend/src/components/main/Sidebar.jsx
import { useState, useEffect, useCallback } from 'react'
import { NavLink, useLocation } from 'react-router-dom'

const MENU = [
  { label: 'Main', to: '/main' },
  {
    group: '가입관리',
    items: [
      { label: '가입관리',     to: '/subscriptions' },
      { label: '과금기준',     to: '/bill-std' },
      { label: '대표가입 관리', to: '/subscription-main' },
      { label: '특수가입관리', to: '/special-subscription' },
    ],
  },
  {
    group: '시스템 설정',
    items: [
      { label: '사용자관리',   to: '/users' },
      { label: '공통코드관리', to: '/code' },
    ],
  },
  {
    group: '게시판',
    items: [
      { label: 'Q&A', to: '/qna' },
    ],
  },
]

function findGroupForPath(pathname) {
  for (const entry of MENU) {
    if (entry.group && entry.items?.some(item => item.to === pathname)) {
      return entry.group
    }
  }
  return null
}

export default function Sidebar() {
  const location = useLocation()

  const [openGroups, setOpenGroups] = useState(() => {
    const active = findGroupForPath(location.pathname)
    return active ? new Set([active]) : new Set()
  })

  useEffect(() => {
    const active = findGroupForPath(location.pathname)
    if (active) {
      setOpenGroups(prev => {
        if (prev.has(active)) return prev
        return new Set([...prev, active])
      })
    }
  }, [location.pathname])

  const toggleGroup = useCallback((group) => {
    setOpenGroups(prev => {
      const next = new Set(prev)
      if (next.has(group)) next.delete(group)
      else next.add(group)
      return next
    })
  }, [])

  const renderNavLink = (label, to) =>
    to ? (
      <NavLink
        key={label}
        to={to}
        className={() => {
          const isActive = location.pathname === to
          return `block px-4 py-2 text-sm transition-colors ${
            isActive
              ? 'text-[#2563EB] bg-blue-50 font-medium'
              : 'text-gray-600 hover:bg-gray-50 hover:text-gray-800'
          }`
        }}
      >
        {label}
      </NavLink>
    ) : (
      <span
        key={label}
        className="block px-4 py-2 text-sm text-gray-300 cursor-not-allowed"
      >
        {label}
      </span>
    )

  return (
    <aside className="w-56 bg-white border-r border-gray-200 flex-shrink-0 overflow-y-auto">
      <nav className="py-4">
        {/* 최상단 단독 항목 */}
        {MENU.filter(m => m.to !== undefined && m.label).map(({ label, to }) => (
          <div key={label} className="mb-2">
            {renderNavLink(label, to)}
          </div>
        ))}
        {/* 그룹 항목 (아코디언) */}
        {MENU.filter(m => m.group).map(({ group, items }) => {
          const isOpen = openGroups.has(group)
          return (
            <div key={group} className="mb-1">
              <button
                type="button"
                onClick={() => toggleGroup(group)}
                className="w-full flex items-center justify-between px-4 py-2 text-sm font-semibold text-gray-500 uppercase tracking-wider hover:bg-gray-50 transition-colors"
              >
                <span>{group}</span>
                <span className="text-xs text-gray-400">{isOpen ? '▾' : '▸'}</span>
              </button>
              {isOpen && items.map(({ label, to }) => renderNavLink(label, to))}
            </div>
          )
        })}
      </nav>
    </aside>
  )
}
