// frontend/src/pages/CommonCodePage.jsx
import { useState } from 'react'
import { useAuth } from '../context/AuthContext'
import useCommonCode from '../hooks/useCommonCode'
import MainLayout from '../components/common/MainLayout'
import Toast from '../components/common/Toast'
import ConfirmDialog from '../components/common/ConfirmDialog'
import CommonCodeList from '../components/common-code/CommonCodeList'
import CommonDtlCodeList from '../components/common-code/CommonDtlCodeList'
import CommonCodeForm from '../components/common-code/CommonCodeForm'
import CommonDtlCodeForm from '../components/common-code/CommonDtlCodeForm'
import CommonCodeActionBar from '../components/common-code/CommonCodeActionBar'

const EMPTY_CODE_FORM = { commonCode: '', commonCodeNm: '', effStartDt: '', effEndDt: '', remark: '' }
const EMPTY_DTL_FORM  = { commonDtlCode: '', commonDtlCodeNm: '', sortOrder: 0, effStartDt: '', effEndDt: '', remark: '' }

export default function CommonCodePage() {
  const { user } = useAuth()
  const {
    codes, details, isLoading,
    fetchCodes, fetchDetails,
    createCode, updateCode, deleteCode,
    createDetail, updateDetail, deleteDetail,
  } = useCommonCode()

  const [searchCode, setSearchCode]     = useState('')
  const [searchCodeNm, setSearchCodeNm] = useState('')
  const [selectedCode, setSelectedCode] = useState(null)
  const [selectedDtl, setSelectedDtl]   = useState(null)
  const [codeForm, setCodeForm]         = useState(EMPTY_CODE_FORM)
  const [dtlForm, setDtlForm]           = useState(EMPTY_DTL_FORM)
  const [codeMode, setCodeMode]           = useState('view')   // 'new' | 'edit' | 'view'
  const [dtlMode, setDtlMode]             = useState('view')
  const [dtlConfirmOpen, setDtlConfirmOpen] = useState(false)
  const [successMsg, setSuccessMsg]       = useState(null)
  const [errorMsg, setErrorMsg]           = useState(null)

  const clearMessages = () => { setSuccessMsg(null); setErrorMsg(null) }

  const handleSearch = async () => {
    clearMessages()
    try {
      const params = {}
      if (searchCode)   params.commonCode   = searchCode
      if (searchCodeNm) params.commonCodeNm = searchCodeNm
      await fetchCodes(params)
      setSelectedCode(null)
      setSelectedDtl(null)
      setCodeForm(EMPTY_CODE_FORM)
      setDtlForm(EMPTY_DTL_FORM)
      setCodeMode('view')
      setDtlMode('view')
    } catch {
      setErrorMsg('조회에 실패했습니다.')
    }
  }

  const handleCodeRowClick = async (code) => {
    setSelectedCode(code)
    setCodeForm({ ...code })
    setSelectedDtl(null)
    setDtlForm(EMPTY_DTL_FORM)
    setCodeMode('edit')
    setDtlMode('view')
    try {
      await fetchDetails(code.commonCode)
    } catch {
      setErrorMsg('상세코드 조회에 실패했습니다.')
    }
  }

  const handleDtlRowClick = (dtl) => {
    setSelectedDtl(dtl)
    setDtlForm({ ...dtl })
    setDtlMode('edit')
  }

  const handleCodeFormChange = (e) => {
    const { name, value } = e.target
    setCodeForm(prev => ({ ...prev, [name]: value }))
  }

  const handleDtlFormChange = (e) => {
    const { name, value } = e.target
    setDtlForm(prev => ({ ...prev, [name]: name === 'sortOrder' ? Number(value) : value }))
  }

  const handleCodeNewClick = () => {
    setCodeMode('new')
    setCodeForm(EMPTY_CODE_FORM)
  }

  const handleDtlDeleteConfirm = async () => {
    setDtlConfirmOpen(false)
    clearMessages()
    try {
      await deleteDetail(selectedCode.commonCode, selectedDtl.commonDtlCode)
      setSelectedDtl(null)
      setDtlForm(EMPTY_DTL_FORM)
      setDtlMode('view')
      await fetchDetails(selectedCode.commonCode)
      setSuccessMsg('상세코드가 삭제되었습니다.')
    } catch {
      setErrorMsg('상세코드 삭제에 실패했습니다.')
    }
  }

  const handleSave = async () => {
    clearMessages()
    const createdBy = user?.userId ?? 'SYSTEM'
    try {
      if (codeMode === 'new') {
        await createCode({ ...codeForm, createdBy })
        setSuccessMsg('공통코드가 등록되었습니다.')
        setCodeMode('view')
        const params = {}
        if (searchCode)   params.commonCode   = searchCode
        if (searchCodeNm) params.commonCodeNm = searchCodeNm
        await fetchCodes(params)
        setCodeForm(EMPTY_CODE_FORM)
      } else if (codeMode === 'edit') {
        await updateCode(codeForm.commonCode, { ...codeForm, createdBy })
        setSuccessMsg('공통코드가 수정되었습니다.')
        const params = {}
        if (searchCode)   params.commonCode   = searchCode
        if (searchCodeNm) params.commonCodeNm = searchCodeNm
        await fetchCodes(params)
      }
    } catch (err) {
      setErrorMsg(err?.response?.data?.message || '저장에 실패했습니다.')
      return
    }

    if (dtlMode !== 'view' && selectedCode) {
      try {
        if (dtlMode === 'new') {
          await createDetail(selectedCode.commonCode, { ...dtlForm, createdBy })
          setSuccessMsg('상세코드가 등록되었습니다.')
          setDtlMode('view')
          setDtlForm(EMPTY_DTL_FORM)
        } else if (dtlMode === 'edit') {
          await updateDetail(selectedCode.commonCode, dtlForm.commonDtlCode, { ...dtlForm, createdBy })
          setSuccessMsg('상세코드가 수정되었습니다.')
        }
        await fetchDetails(selectedCode.commonCode)
      } catch (err) {
        setErrorMsg(err?.response?.data?.message || '상세코드 저장에 실패했습니다.')
      }
    }
  }

  const handleCancel = () => {
    setCodeMode('view')
    setDtlMode('view')
    setCodeForm(selectedCode ? { ...selectedCode } : EMPTY_CODE_FORM)
    setDtlForm(selectedDtl ? { ...selectedDtl } : EMPTY_DTL_FORM)
  }

  const activeMode = codeMode !== 'view' || dtlMode !== 'view' ? 'active' : 'view'

  return (
    <MainLayout>
      <Toast message={successMsg} type="success" onClose={() => setSuccessMsg(null)} />
      <Toast message={errorMsg}   type="error"   onClose={() => setErrorMsg(null)} />

      <div className="space-y-4">
        <h1 className="text-xl font-bold text-gray-800">공통코드 관리</h1>

        {/* 조회영역 */}
        <div className="bg-white rounded-lg shadow-sm p-4 flex items-end gap-4">
          <div>
            <label className="block text-xs text-gray-500 mb-1">공통코드</label>
            <input
              value={searchCode}
              onChange={e => setSearchCode(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleSearch()}
              className="h-8 px-3 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400"
            />
          </div>
          <div>
            <label className="block text-xs text-gray-500 mb-1">공통코드명</label>
            <input
              value={searchCodeNm}
              onChange={e => setSearchCodeNm(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleSearch()}
              className="h-8 px-3 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400"
            />
          </div>
          <button
            onClick={handleSearch}
            disabled={isLoading}
            className="h-8 px-4 bg-blue-600 text-white text-sm rounded disabled:opacity-50"
          >
            조회
          </button>
        </div>

        {/* 마스터-디테일 목록 영역 */}
        <div className="flex gap-4">
          {/* 좌측: 공통코드 목록 */}
          <div className="w-1/3 space-y-2">
            <CommonCodeList
              codes={codes}
              selectedCode={selectedCode?.commonCode}
              onRowClick={handleCodeRowClick}
            />
            <div className="flex justify-end">
              <button
                onClick={handleCodeNewClick}
                className="h-8 px-4 bg-blue-600 text-white text-sm rounded"
              >
                등록
              </button>
            </div>
          </div>

          {/* 우측: 공통상세코드 목록 */}
          <div className="w-2/3 space-y-2">
            <CommonDtlCodeList
              details={details}
              selectedDtl={selectedDtl?.commonDtlCode}
              onRowClick={handleDtlRowClick}
            />
            <div className="flex justify-end gap-2">
              <button
                onClick={() => { setDtlMode('new'); setDtlForm(EMPTY_DTL_FORM) }}
                disabled={!selectedCode}
                className="h-8 px-4 bg-blue-600 text-white text-sm rounded disabled:opacity-40 disabled:cursor-not-allowed"
              >
                등록
              </button>
              <button
                onClick={() => selectedDtl && setDtlMode('edit')}
                disabled={!selectedDtl}
                className="h-8 px-4 border border-gray-300 text-sm rounded text-gray-600 hover:bg-gray-50 disabled:opacity-40 disabled:cursor-not-allowed"
              >
                수정
              </button>
              <button
                onClick={() => selectedDtl && setDtlConfirmOpen(true)}
                disabled={!selectedDtl}
                className="h-8 px-4 border border-red-300 text-sm rounded text-red-600 hover:bg-red-50 disabled:opacity-40 disabled:cursor-not-allowed"
              >
                삭제
              </button>
            </div>
          </div>
        </div>

        {/* 폼 영역 */}
        {codeMode !== 'view' && (
          <CommonCodeForm
            data={codeForm}
            onChange={handleCodeFormChange}
            isEdit={codeMode === 'edit'}
          />
        )}
        {dtlMode !== 'view' && (
          <CommonDtlCodeForm
            data={dtlForm}
            onChange={handleDtlFormChange}
            isEdit={dtlMode === 'edit'}
          />
        )}
      </div>

      <CommonCodeActionBar
        onSave={handleSave}
        onCancel={handleCancel}
        activeMode={activeMode}
      />

      {dtlConfirmOpen && (
        <ConfirmDialog
          message="상세코드를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다."
          onConfirm={handleDtlDeleteConfirm}
          onCancel={() => setDtlConfirmOpen(false)}
        />
      )}
    </MainLayout>
  )
}

// frontend-vue/src/pages/CommonCodePage.vue
<template>
  <MainLayout>
    <Toast :message="successMsg" type="success" @close="successMsg = ''" />
    <Toast :message="errorMsg" type="error" @close="errorMsg = ''" />

    <div class="space-y-4">
      <h1 class="text-xl font-bold text-gray-800">공통코드 관리</h1>

      <!-- 조회영역 -->
      <div class="bg-white rounded-lg shadow-sm p-4 flex items-end gap-4">
        <div>
          <label class="block text-xs text-gray-500 mb-1">공통코드</label>
          <input v-model="searchCode" @keydown.enter="handleSearch"
            class="h-8 px-3 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400" />
        </div>
        <div>
          <label class="block text-xs text-gray-500 mb-1">공통코드명</label>
          <input v-model="searchCodeNm" @keydown.enter="handleSearch"
            class="h-8 px-3 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400" />
        </div>
        <button @click="handleSearch" :disabled="isLoading"
          class="h-8 px-4 bg-blue-600 text-white text-sm rounded disabled:opacity-50">조회</button>
      </div>

      <!-- 마스터-디테일 목록 -->
      <div class="flex gap-4">
        <!-- 좌측: 공통코드 목록 -->
        <div class="w-1/3 space-y-2">
          <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
            <table class="w-full text-sm border-collapse">
              <thead class="bg-gray-50 border-t border-gray-300 border-b border-gray-300">
                <tr>
                  <th class="px-3 py-1.5 text-left text-xs font-medium text-gray-500">공통코드</th>
                  <th class="px-3 py-1.5 text-left text-xs font-medium text-gray-500">공통코드명</th>
                </tr>
              </thead>
            </table>
            <div class="max-h-[40rem] overflow-y-auto">
              <table class="w-full text-sm border-collapse">
                <tbody>
                  <tr v-if="codes.length === 0">
                    <td colspan="2" class="px-3 py-4 text-center text-xs text-gray-400">데이터가 없습니다.</td>
                  </tr>
                  <tr v-for="code in codes" :key="code.commonCode"
                    @click="handleCodeRowClick(code)"
                    :class="['h-7 cursor-pointer border-b border-gray-200',
                      selectedCode?.commonCode === code.commonCode ? 'bg-blue-50 text-blue-900' : 'hover:bg-gray-50 text-gray-800']">
                    <td class="px-3 text-xs">{{ code.commonCode }}</td>
                    <td class="px-3 text-xs">{{ code.commonCodeNm }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="flex justify-end">
            <button @click="handleCodeNewClick" class="h-8 px-4 bg-blue-600 text-white text-sm rounded">등록</button>
          </div>
        </div>

        <!-- 우측: 상세코드 목록 -->
        <div class="w-2/3 space-y-2">
          <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
            <table class="w-full text-sm border-collapse">
              <thead class="bg-gray-50 border-t border-gray-300 border-b border-gray-300">
                <tr>
                  <th class="px-3 py-1.5 text-left text-xs font-medium text-gray-500">상세코드</th>
                  <th class="px-3 py-1.5 text-left text-xs font-medium text-gray-500">상세코드명</th>
                  <th class="px-3 py-1.5 text-left text-xs font-medium text-gray-500 w-16">정렬</th>
                </tr>
              </thead>
            </table>
            <div class="max-h-[40rem] overflow-y-auto">
              <table class="w-full text-sm border-collapse">
                <tbody>
                  <tr v-if="details.length === 0">
                    <td colspan="3" class="px-3 py-4 text-center text-xs text-gray-400">데이터가 없습니다.</td>
                  </tr>
                  <tr v-for="dtl in details" :key="dtl.commonDtlCode"
                    @click="handleDtlRowClick(dtl)"
                    :class="['h-7 cursor-pointer border-b border-gray-200',
                      selectedDtl?.commonDtlCode === dtl.commonDtlCode ? 'bg-blue-50 text-blue-900' : 'hover:bg-gray-50 text-gray-800']">
                    <td class="px-3 text-xs">{{ dtl.commonDtlCode }}</td>
                    <td class="px-3 text-xs">{{ dtl.commonDtlCodeNm }}</td>
                    <td class="px-3 text-xs text-center">{{ dtl.sortOrder }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="flex justify-end gap-2">
            <button @click="dtlMode = 'new'; Object.assign(dtlForm, EMPTY_DTL_FORM)"
              :disabled="!selectedCode"
              class="h-8 px-4 bg-blue-600 text-white text-sm rounded disabled:opacity-40 disabled:cursor-not-allowed">등록</button>
            <button @click="selectedDtl && (dtlMode = 'edit')"
              :disabled="!selectedDtl"
              class="h-8 px-4 border border-gray-300 text-sm rounded text-gray-600 hover:bg-gray-50 disabled:opacity-40 disabled:cursor-not-allowed">수정</button>
            <button @click="selectedDtl && (dtlConfirmOpen = true)"
              :disabled="!selectedDtl"
              class="h-8 px-4 border border-red-300 text-sm rounded text-red-600 hover:bg-red-50 disabled:opacity-40 disabled:cursor-not-allowed">삭제</button>
          </div>
        </div>
      </div>

      <!-- 공통코드 폼 -->
      <div v-if="codeMode !== 'view'" class="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
        <h2 class="text-sm font-semibold text-gray-700 mb-3">공통코드 그룹 정보</h2>
        <div class="grid grid-cols-6 gap-x-4 gap-y-3">
          <label class="col-span-1 flex items-center text-xs text-gray-500">공통코드</label>
          <div class="col-span-1">
            <input v-model="codeForm.commonCode" :readonly="codeMode === 'edit'"
              :class="['w-full h-8 border rounded px-2 text-sm focus:outline-none focus:border-blue-400',
                codeMode === 'edit' ? 'border-gray-200 bg-gray-50 text-gray-500' : 'border-gray-300']" />
          </div>
          <label class="col-span-1 flex items-center text-xs text-gray-500">공통코드명</label>
          <div class="col-span-1">
            <input v-model="codeForm.commonCodeNm" class="w-full h-8 border border-gray-300 rounded px-2 text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <label class="col-span-1 flex items-center text-xs text-gray-500">유효시작일</label>
          <div class="col-span-1">
            <input type="datetime-local" v-model="codeForm.effStartDt" class="w-full h-8 border border-gray-300 rounded px-2 text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <label class="col-span-1 flex items-center text-xs text-gray-500">유효종료일</label>
          <div class="col-span-1">
            <input type="datetime-local" v-model="codeForm.effEndDt" class="w-full h-8 border border-gray-300 rounded px-2 text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <label class="col-span-1 flex items-center text-xs text-gray-500">비고</label>
          <div class="col-span-3">
            <textarea v-model="codeForm.remark" rows="2" class="w-full border border-gray-300 rounded px-2 py-1 text-sm focus:outline-none focus:border-blue-400 resize-none" />
          </div>
        </div>
      </div>

      <!-- 상세코드 폼 -->
      <div v-if="dtlMode !== 'view'" class="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
        <h2 class="text-sm font-semibold text-gray-700 mb-3">공통상세코드 정보</h2>
        <div class="grid grid-cols-6 gap-x-4 gap-y-3">
          <label class="col-span-1 flex items-center text-xs text-gray-500">상세코드</label>
          <div class="col-span-1">
            <input v-model="dtlForm.commonDtlCode" :readonly="dtlMode === 'edit'"
              :class="['w-full h-8 border rounded px-2 text-sm focus:outline-none focus:border-blue-400',
                dtlMode === 'edit' ? 'border-gray-200 bg-gray-50 text-gray-500' : 'border-gray-300']" />
          </div>
          <label class="col-span-1 flex items-center text-xs text-gray-500">상세코드명</label>
          <div class="col-span-1">
            <input v-model="dtlForm.commonDtlCodeNm" class="w-full h-8 border border-gray-300 rounded px-2 text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <label class="col-span-1 flex items-center text-xs text-gray-500">정렬순서</label>
          <div class="col-span-1">
            <input type="number" v-model.number="dtlForm.sortOrder" class="w-full h-8 border border-gray-300 rounded px-2 text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <label class="col-span-1 flex items-center text-xs text-gray-500">유효시작일</label>
          <div class="col-span-1">
            <input type="datetime-local" v-model="dtlForm.effStartDt" class="w-full h-8 border border-gray-300 rounded px-2 text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <label class="col-span-1 flex items-center text-xs text-gray-500">유효종료일</label>
          <div class="col-span-1">
            <input type="datetime-local" v-model="dtlForm.effEndDt" class="w-full h-8 border border-gray-300 rounded px-2 text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <label class="col-span-1 flex items-center text-xs text-gray-500">비고</label>
          <div class="col-span-3">
            <textarea v-model="dtlForm.remark" rows="2" class="w-full border border-gray-300 rounded px-2 py-1 text-sm focus:outline-none focus:border-blue-400 resize-none" />
          </div>
        </div>
      </div>
    </div>

    <FloatingActionBar v-if="codeMode !== 'view' || dtlMode !== 'view'">
      <button @click="handleCancel"
        class="h-8 px-4 border border-gray-300 text-sm rounded text-gray-600 hover:bg-gray-50 transition-colors">취소</button>
      <button @click="handleSave"
        class="h-8 px-6 bg-blue-600 hover:bg-blue-700 text-white text-sm rounded transition-colors">저장</button>
    </FloatingActionBar>

    <ConfirmDialog
      v-if="dtlConfirmOpen"
      message="상세코드를 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다."
      @confirm="handleDtlDeleteConfirm"
      @cancel="dtlConfirmOpen = false"
    />
  </MainLayout>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { useAuthStore } from '../stores/auth'
import { commonCodeApi } from '../api/commonCodeApi'
import MainLayout from '../components/common/MainLayout.vue'
import Toast from '../components/common/Toast.vue'
import FloatingActionBar from '../components/common/FloatingActionBar.vue'
import ConfirmDialog from '../components/common/ConfirmDialog.vue'

const auth = useAuthStore()

const EMPTY_CODE_FORM = { commonCode: '', commonCodeNm: '', effStartDt: '', effEndDt: '', remark: '' }
const EMPTY_DTL_FORM = { commonDtlCode: '', commonDtlCodeNm: '', sortOrder: 0, effStartDt: '', effEndDt: '', remark: '' }

const searchCode = ref('')
const searchCodeNm = ref('')
const codes = ref([])
const details = ref([])
const selectedCode = ref(null)
const selectedDtl = ref(null)
const codeForm = reactive({ ...EMPTY_CODE_FORM })
const dtlForm = reactive({ ...EMPTY_DTL_FORM })
const codeMode = ref('view')
const dtlMode = ref('view')
const dtlConfirmOpen = ref(false)
const isLoading = ref(false)
const successMsg = ref('')
const errorMsg = ref('')

const clearMessages = () => { successMsg.value = ''; errorMsg.value = '' }

const getSearchParams = () => {
  const params = {}
  if (searchCode.value) params.commonCode = searchCode.value
  if (searchCodeNm.value) params.commonCodeNm = searchCodeNm.value
  return params
}

onMounted(async () => {
  try { codes.value = await commonCodeApi.getAll() } catch {}
})

const handleSearch = async () => {
  clearMessages()
  isLoading.value = true
  try {
    codes.value = await commonCodeApi.getAll(getSearchParams())
    selectedCode.value = null
    selectedDtl.value = null
    details.value = []
    Object.assign(codeForm, EMPTY_CODE_FORM)
    Object.assign(dtlForm, EMPTY_DTL_FORM)
    codeMode.value = 'view'
    dtlMode.value = 'view'
  } catch { errorMsg.value = '조회에 실패했습니다.' }
  finally { isLoading.value = false }
}

const handleCodeRowClick = async (code) => {
  selectedCode.value = code
  Object.assign(codeForm, { ...code })
  selectedDtl.value = null
  Object.assign(dtlForm, EMPTY_DTL_FORM)
  codeMode.value = 'edit'
  dtlMode.value = 'view'
  try { details.value = await commonCodeApi.getDetails(code.commonCode) }
  catch { errorMsg.value = '상세코드 조회에 실패했습니다.' }
}

const handleDtlRowClick = (dtl) => {
  selectedDtl.value = dtl
  Object.assign(dtlForm, { ...dtl })
  dtlMode.value = 'edit'
}

const handleCodeNewClick = () => {
  codeMode.value = 'new'
  Object.assign(codeForm, EMPTY_CODE_FORM)
}

const handleDtlDeleteConfirm = async () => {
  dtlConfirmOpen.value = false
  clearMessages()
  try {
    await commonCodeApi.deleteDetail(selectedCode.value.commonCode, selectedDtl.value.commonDtlCode)
    selectedDtl.value = null
    Object.assign(dtlForm, EMPTY_DTL_FORM)
    dtlMode.value = 'view'
    details.value = await commonCodeApi.getDetails(selectedCode.value.commonCode)
    successMsg.value = '상세코드가 삭제되었습니다.'
  } catch { errorMsg.value = '상세코드 삭제에 실패했습니다.' }
}

const handleSave = async () => {
  clearMessages()
  const createdBy = auth.user?.userId ?? 'SYSTEM'
  try {
    if (codeMode.value === 'new') {
      await commonCodeApi.create({ ...codeForm, createdBy })
      successMsg.value = '공통코드가 등록되었습니다.'
      codeMode.value = 'view'
      codes.value = await commonCodeApi.getAll(getSearchParams())
      Object.assign(codeForm, EMPTY_CODE_FORM)
    } else if (codeMode.value === 'edit') {
      await commonCodeApi.update(codeForm.commonCode, { ...codeForm, createdBy })
      successMsg.value = '공통코드가 수정되었습니다.'
      codes.value = await commonCodeApi.getAll(getSearchParams())
    }
  } catch (err) {
    errorMsg.value = err?.response?.data?.message || '저장에 실패했습니다.'
    return
  }

  if (dtlMode.value !== 'view' && selectedCode.value) {
    try {
      if (dtlMode.value === 'new') {
        await commonCodeApi.createDetail(selectedCode.value.commonCode, { ...dtlForm, createdBy })
        successMsg.value = '상세코드가 등록되었습니다.'
        dtlMode.value = 'view'
        Object.assign(dtlForm, EMPTY_DTL_FORM)
      } else if (dtlMode.value === 'edit') {
        await commonCodeApi.updateDetail(selectedCode.value.commonCode, dtlForm.commonDtlCode, { ...dtlForm, createdBy })
        successMsg.value = '상세코드가 수정되었습니다.'
      }
      details.value = await commonCodeApi.getDetails(selectedCode.value.commonCode)
    } catch (err) {
      errorMsg.value = err?.response?.data?.message || '상세코드 저장에 실패했습니다.'
    }
  }
}

const handleCancel = () => {
  codeMode.value = 'view'
  dtlMode.value = 'view'
  Object.assign(codeForm, selectedCode.value ? { ...selectedCode.value } : EMPTY_CODE_FORM)
  Object.assign(dtlForm, selectedDtl.value ? { ...selectedDtl.value } : EMPTY_DTL_FORM)
}
</script>
