// frontend-vue/src/pages/BillStdPage.vue
<template>
  <MainLayout>
    <Toast :message="successMsg" type="success" @close="successMsg = ''" />
    <Toast :message="errorMsg" type="error" @close="errorMsg = ''" />

    <div class="space-y-4">
      <h1 class="text-xl font-bold text-gray-800">가입별 과금기준 관리</h1>

      <!-- 조회영역 -->
      <div class="bg-gray-50 border border-gray-200 rounded-lg p-3">
        <div class="flex items-center gap-2">
          <div>
            <label class="block text-xs text-gray-500 mb-1">검색유형</label>
            <select v-model="searchType" class="h-8 px-2 border border-gray-300 rounded text-sm bg-white">
              <option value="subsId">가입ID</option>
              <option value="billStdId">과금기준ID</option>
            </select>
          </div>
          <div>
            <label class="block text-xs text-gray-500 mb-1">검색어</label>
            <input v-model="keyword" @keydown.enter="handleSearch"
              class="h-8 px-3 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <div class="self-end">
            <button @click="handleSearch" :disabled="isSearching"
              class="h-8 px-4 bg-blue-600 text-white text-sm rounded hover:bg-blue-700 disabled:opacity-60">조회</button>
          </div>
        </div>
      </div>

      <!-- 입력 폼 -->
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
        <h3 class="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-3">과금기준 정보</h3>
        <div class="grid grid-cols-3 gap-x-4 gap-y-3">
          <div>
            <label class="block text-xs text-gray-500 mb-1">과금기준ID</label>
            <input v-model="formData.billStdId" readonly class="w-full h-8 px-2 border border-gray-200 rounded text-sm bg-gray-50 text-gray-400" />
          </div>
          <div>
            <label class="block text-xs text-gray-500 mb-1">가입ID</label>
            <input v-model="formData.subsId" class="w-full h-8 px-2 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <div>
            <label class="block text-xs text-gray-500 mb-1">서비스코드</label>
            <input v-model="formData.svcCd" class="w-full h-8 px-2 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <div>
            <label class="block text-xs text-gray-500 mb-1">적용시작일</label>
            <input v-model="formData.effStartDt" class="w-full h-8 px-2 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <div>
            <label class="block text-xs text-gray-500 mb-1">적용종료일</label>
            <input v-model="formData.effEndDt" class="w-full h-8 px-2 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <div>
            <label class="block text-xs text-gray-500 mb-1">계약용량(KMH)</label>
            <input v-model="formData.cntrcCapKmh" class="w-full h-8 px-2 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <div>
            <label class="block text-xs text-gray-500 mb-1">계약금액</label>
            <input v-model="formData.cntrcAmt" class="w-full h-8 px-2 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <div>
            <label class="block text-xs text-gray-500 mb-1">계량단가</label>
            <input v-model="formData.meteringUnitPriceAmt" class="w-full h-8 px-2 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-400" />
          </div>
          <div>
            <label class="block text-xs text-gray-500 mb-1">최종적용여부</label>
            <select v-model="formData.lastEffYn" class="w-full h-8 px-2 border border-gray-300 rounded text-sm bg-white">
              <option value="Y">Y</option>
              <option value="N">N</option>
            </select>
          </div>
        </div>
      </div>
    </div>

    <FloatingActionBar>
      <button @click="handleSave" class="h-8 px-6 bg-blue-600 text-white text-sm rounded hover:bg-blue-700">저장</button>
      <button @click="handleChange" class="h-8 px-6 bg-blue-600 text-white text-sm rounded hover:bg-blue-700">변경</button>
      <button @click="handleDeleteClick" class="h-8 px-4 border border-red-300 text-sm rounded text-red-600 hover:bg-red-50">삭제</button>
    </FloatingActionBar>

    <ConfirmDialog
      v-if="confirmOpen"
      message="삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다."
      @confirm="executeDelete"
      @cancel="confirmOpen = false"
    />
  </MainLayout>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { useAuthStore } from '../stores/auth'
import { getBillStdBySubsId, getBillStd, createBillStd, updateBillStd, deleteBillStd } from '../api/billStdApi'
import MainLayout from '../components/common/MainLayout.vue'
import Toast from '../components/common/Toast.vue'
import FloatingActionBar from '../components/common/FloatingActionBar.vue'
import ConfirmDialog from '../components/common/ConfirmDialog.vue'

const auth = useAuthStore()

const EMPTY_FORM = {
  billStdId: '', subsId: '', svcCd: '', lastEffYn: 'Y',
  effStartDt: '', effEndDt: '', meteringUnitPriceAmt: '',
  cntrcCapKmh: '', cntrcAmt: '',
}

const formData = reactive({ ...EMPTY_FORM })
const keyword = ref('')
const searchType = ref('subsId')
const errorMsg = ref('')
const successMsg = ref('')
const confirmOpen = ref(false)
const isSearching = ref(false)

const clearMessages = () => { errorMsg.value = ''; successMsg.value = '' }

const toFormData = (dto) => {
  Object.keys(EMPTY_FORM).forEach(key => {
    formData[key] = dto[key] != null ? String(dto[key]) : ''
  })
}

const toRequestDto = () => ({
  ...formData,
  meteringUnitPriceAmt: formData.meteringUnitPriceAmt ? parseFloat(formData.meteringUnitPriceAmt) : null,
  cntrcCapKmh: formData.cntrcCapKmh ? parseFloat(formData.cntrcCapKmh) : null,
  cntrcAmt: formData.cntrcAmt ? parseFloat(formData.cntrcAmt) : null,
  createdBy: auth.user?.userId ?? 'SYSTEM',
})

const handleSearch = async () => {
  clearMessages()
  if (!keyword.value.trim()) { errorMsg.value = '검색어를 입력해 주세요.'; return }
  isSearching.value = true
  try {
    const found = searchType.value === 'subsId'
      ? await getBillStdBySubsId(keyword.value.trim())
      : await getBillStd(keyword.value.trim())
    toFormData(found)
    successMsg.value = '조회가 완료되었습니다.'
  } catch (err) {
    errorMsg.value = err?.response?.status === 404 ? '조회 결과가 없습니다.' : '서버와 연결할 수 없습니다.'
    Object.assign(formData, EMPTY_FORM)
  } finally { isSearching.value = false }
}

const handleSave = async () => {
  clearMessages()
  try {
    const created = await createBillStd(toRequestDto())
    toFormData(created)
    successMsg.value = '저장이 완료되었습니다.'
  } catch (err) {
    errorMsg.value = err?.response?.data?.message || '저장에 실패했습니다.'
  }
}

const handleChange = async () => {
  if (!formData.billStdId) { errorMsg.value = '조회 후 변경할 수 있습니다.'; return }
  clearMessages()
  try {
    const updated = await updateBillStd(formData.billStdId, toRequestDto())
    toFormData(updated)
    successMsg.value = '변경이 완료되었습니다.'
  } catch (err) {
    errorMsg.value = err?.response?.data?.message || '변경에 실패했습니다.'
  }
}

const handleDeleteClick = () => {
  if (!formData.billStdId) { errorMsg.value = '조회 후 삭제할 수 있습니다.'; return }
  clearMessages()
  confirmOpen.value = true
}

const executeDelete = async () => {
  confirmOpen.value = false
  try {
    await deleteBillStd(formData.billStdId)
    Object.assign(formData, EMPTY_FORM)
    successMsg.value = '삭제가 완료되었습니다.'
  } catch (err) {
    errorMsg.value = err?.response?.status === 409 ? '다른 이력이 존재하여 삭제할 수 없습니다.' : '삭제에 실패했습니다.'
  }
}
</script>

// frontend/src/pages/BillStdPage.jsx
import { useState } from 'react'
import useBillStd from '../hooks/useBillStd'
import MainLayout from '../components/common/MainLayout'
import Toast from '../components/common/Toast'
import ConfirmDialog from '../components/common/ConfirmDialog'
import BillStdSearchBar from '../components/billstd/BillStdSearchBar'
import BillStdForm from '../components/billstd/BillStdForm'
import BillStdActionBar from '../components/billstd/BillStdActionBar'

const EMPTY_FORM = {
  billStdId: '', subsId: '', billStdRegDt: '', svcCd: '', lastEffYn: 'Y',
  effStartDt: '', effEndDt: '', stdRegStatCd: '', billStdStatCd: '',
  pwrMetCalcMethCd: '', uprcDetMethCd: '', meteringUnitPriceAmt: '', billQty: '',
  pueDetMethCd: '', pue1Rt: '', pue2Rt: '',
  firstDscRt: '', secondDscRt: '', lossCompRt: '',
  cntrcCapKmh: '', cntrcAmt: '', dscAmt: '', dailyUnitPrice: '',
}

// API 응답 → 폼 문자열 변환
const toFormData = (dto) =>
  Object.fromEntries(
    Object.keys(EMPTY_FORM).map((key) => [key, dto[key] != null ? String(dto[key]) : ''])
  )

// 폼 문자열 → API 요청 객체 변환
const toRequestDto = (form) => ({
  subsId:               form.subsId               || null,
  billStdRegDt:         form.billStdRegDt         || null,
  svcCd:                form.svcCd                || null,
  lastEffYn:            form.lastEffYn            || null,
  effStartDt:           form.effStartDt           || null,
  effEndDt:             form.effEndDt             || null,
  stdRegStatCd:         form.stdRegStatCd         || null,
  billStdStatCd:        form.billStdStatCd        || null,
  pwrMetCalcMethCd:     form.pwrMetCalcMethCd     || null,
  uprcDetMethCd:        form.uprcDetMethCd        || null,
  meteringUnitPriceAmt: form.meteringUnitPriceAmt ? parseFloat(form.meteringUnitPriceAmt) : null,
  billQty:              form.billQty              ? parseFloat(form.billQty)              : null,
  pueDetMethCd:         form.pueDetMethCd         || null,
  pue1Rt:               form.pue1Rt               ? parseFloat(form.pue1Rt)               : null,
  pue2Rt:               form.pue2Rt               ? parseFloat(form.pue2Rt)               : null,
  firstDscRt:           form.firstDscRt           ? parseFloat(form.firstDscRt)           : null,
  secondDscRt:          form.secondDscRt          ? parseFloat(form.secondDscRt)          : null,
  lossCompRt:           form.lossCompRt           ? parseFloat(form.lossCompRt)           : null,
  cntrcCapKmh:          form.cntrcCapKmh          ? parseFloat(form.cntrcCapKmh)          : null,
  cntrcAmt:             form.cntrcAmt             ? parseFloat(form.cntrcAmt)             : null,
  dscAmt:               form.dscAmt               ? parseFloat(form.dscAmt)               : null,
  dailyUnitPrice:       form.dailyUnitPrice       ? parseFloat(form.dailyUnitPrice)       : null,
  createdBy:            'SYSTEM',
})

export default function BillStdPage() {
  const { isSearching, searchBySubsId, searchById, handleCreate, handleUpdate, handleDelete } = useBillStd()
  const [formData, setFormData]             = useState(EMPTY_FORM)
  const [keyword, setKeyword]               = useState('')
  const [searchType, setSearchType]         = useState('subsId')
  const [errorMsg, setErrorMsg]       = useState(null)
  const [successMsg, setSuccessMsg]   = useState(null)
  const [confirmOpen, setConfirmOpen] = useState(false)

  const clearMessages = () => { setErrorMsg(null); setSuccessMsg(null) }

  const handleSearch = async () => {
    clearMessages()
    if (!keyword.trim()) {
      setErrorMsg('검색어를 입력해 주세요.')
      return
    }
    try {
      const found = searchType === 'subsId'
        ? await searchBySubsId(keyword.trim())
        : await searchById(keyword.trim())
      setFormData(toFormData(found))
      setSuccessMsg('조회가 완료되었습니다.')
    } catch (err) {
      const status = err?.response?.status
      setErrorMsg(status === 404 ? '조회 결과가 없습니다.' : '서버와 연결할 수 없습니다.')
      setFormData(EMPTY_FORM)
    }
  }

  const handleFieldChange = (e) => {
    const { name, value } = e.target
    setFormData((prev) => ({ ...prev, [name]: value }))
  }

  const handleSave = async () => {
    clearMessages()
    try {
      const created = await handleCreate(toRequestDto(formData))
      setFormData(toFormData(created))
      setSuccessMsg('저장이 완료되었습니다.')
    } catch {
      setErrorMsg('저장에 실패했습니다.')
    }
  }

  const handleChange = async () => {
    if (!formData.billStdId) { setErrorMsg('조회 후 변경할 수 있습니다.'); return }
    clearMessages()
    try {
      const updated = await handleUpdate(formData.billStdId, toRequestDto(formData))
      setFormData(toFormData(updated))
      setSuccessMsg('변경이 완료되었습니다.')
    } catch {
      setErrorMsg('변경에 실패했습니다.')
    }
  }

  const handleDeleteClick = () => {
    if (!formData.billStdId) { setErrorMsg('조회 후 삭제할 수 있습니다.'); return }
    clearMessages()
    setConfirmOpen(true)
  }

  const executeDelete = async () => {
    try {
      await handleDelete(formData.billStdId)
      setFormData(EMPTY_FORM)
      setSuccessMsg('삭제가 완료되었습니다.')
    } catch (err) {
      const status = err?.response?.status
      setErrorMsg(
        status === 409
          ? '다른 이력이 존재하여 삭제할 수 없습니다.'
          : '삭제에 실패했습니다.'
      )
    }
  }

  return (
    <MainLayout>
      <Toast message={successMsg} type="success" onClose={() => setSuccessMsg(null)} />
      <Toast message={errorMsg}   type="error"   onClose={() => setErrorMsg(null)} />

      <div className="space-y-4 pb-20">
        <h1 className="text-xl font-bold text-gray-800">가입별 과금기준 관리</h1>

        <BillStdSearchBar
          keyword={keyword}
          onKeywordChange={(e) => setKeyword(e.target.value)}
          searchType={searchType}
          onSearchTypeChange={(e) => setSearchType(e.target.value)}
          onSearch={handleSearch}
          isSearching={isSearching}
        />

        <BillStdForm data={formData} onChange={handleFieldChange} />
      </div>

      <BillStdActionBar
        onSave={handleSave}
        onChange={handleChange}
        onDelete={handleDeleteClick}
      />

      {confirmOpen && (
        <ConfirmDialog
          message="삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다."
          onConfirm={() => { setConfirmOpen(false); executeDelete() }}
          onCancel={() => setConfirmOpen(false)}
        />
      )}
    </MainLayout>
  )
}
