// frontend-vue/src/pages/QnaDetailPage.vue
<template>
  <MainLayout>
    <Toast :message="successMsg" type="success" @close="successMsg = ''" />
    <Toast :message="errorMsg" type="error" @close="errorMsg = ''" />

    <div class="space-y-4">
      <h1 class="text-xl font-bold text-gray-800">{{ isNew ? 'Q&A 등록' : 'Q&A 상세' }}</h1>

      <!-- 게시글 폼 -->
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4 space-y-3">
        <div>
          <label class="block text-xs text-gray-500 mb-1">제목 <span class="text-blue-400">*</span></label>
          <input v-model="form.title" :readonly="!isNew && !isEditing"
            :class="['w-full h-8 border rounded px-3 text-sm focus:outline-none focus:border-blue-400',
              (!isNew && !isEditing) ? 'border-gray-200 bg-gray-50 text-gray-500' : 'border-gray-300']" />
        </div>
        <div>
          <label class="block text-xs text-gray-500 mb-1">내용</label>
          <textarea v-model="form.content" rows="8" :readonly="!isNew && !isEditing"
            :class="['w-full border rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-400 resize-none',
              (!isNew && !isEditing) ? 'border-gray-200 bg-gray-50 text-gray-500' : 'border-gray-300']" />
        </div>
      </div>

      <!-- 댓글 영역 (상세보기 시) -->
      <template v-if="!isNew">
        <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
          <h3 class="text-sm font-semibold text-gray-700 mb-3">댓글</h3>
          <div v-if="comments.length === 0" class="text-center text-xs text-gray-400 py-4">등록된 댓글이 없습니다.</div>
          <div v-else class="space-y-2">
            <div v-for="c in comments" :key="c.commentId"
              :class="['border border-gray-100 rounded p-3 bg-white', c.parentCommentId ? 'ml-8' : '']">
              <div class="flex justify-between items-start">
                <p class="text-sm text-gray-800 flex-1">{{ c.content }}</p>
                <button v-if="c.createdBy === auth.user?.userId" @click="handleCommentDelete(c.commentId)"
                  class="ml-2 text-xs text-red-400 hover:text-red-600">삭제</button>
              </div>
              <span class="text-xs text-gray-400">{{ c.createdBy }} · {{ c.createdDt ? c.createdDt.slice(0, 16) : '' }}</span>
            </div>
          </div>
        </div>

        <!-- 댓글 작성 -->
        <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
          <h3 class="text-sm font-semibold text-gray-700 mb-2">댓글 작성</h3>
          <div class="flex gap-2">
            <textarea v-model="commentContent" rows="3" placeholder="댓글을 입력하세요."
              class="flex-1 border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-400 resize-none" />
            <button @click="handleCommentSubmit"
              class="h-8 self-end px-4 bg-blue-600 text-white text-sm rounded whitespace-nowrap">등록</button>
          </div>
        </div>
      </template>
    </div>

    <FloatingActionBar>
      <button @click="router.push('/qna')"
        class="h-8 px-4 border border-gray-300 text-sm rounded text-gray-600 hover:bg-gray-50 transition-colors">목록</button>
      <button v-if="isOwner && !isNew" @click="confirmOpen = true"
        class="h-8 px-4 text-red-500 hover:text-red-700 hover:bg-red-50 rounded text-sm transition-colors">삭제</button>
      <button v-if="isNew || isOwner" @click="handleActionClick"
        class="h-8 px-6 bg-blue-600 hover:bg-blue-700 text-white text-sm rounded transition-colors">
        {{ isNew ? '저장' : (isEditing ? '수정' : '편집') }}
      </button>
    </FloatingActionBar>

    <ConfirmDialog
      v-if="confirmOpen"
      message="게시글을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다."
      @confirm="handleDelete"
      @cancel="confirmOpen = false"
    />
  </MainLayout>
</template>

<script setup>
import { ref, reactive, computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import { qnaApi } from '../api/qnaApi'
import MainLayout from '../components/common/MainLayout.vue'
import Toast from '../components/common/Toast.vue'
import FloatingActionBar from '../components/common/FloatingActionBar.vue'
import ConfirmDialog from '../components/common/ConfirmDialog.vue'

const route = useRoute()
const router = useRouter()
const auth = useAuthStore()

const isNew = computed(() => !route.params.id)
const form = reactive({ title: '', content: '', createdBy: '' })
const comments = ref([])
const commentContent = ref('')
const isEditing = ref(false)
const confirmOpen = ref(false)
const errorMsg = ref('')
const successMsg = ref('')

const isOwner = computed(() => isNew.value || form.createdBy === auth.user?.userId)

onMounted(async () => {
  if (!isNew.value) {
    try {
      const data = await qnaApi.getOne(route.params.id)
      Object.assign(form, data)
    } catch { errorMsg.value = '게시글을 불러오지 못했습니다.' }
    try { comments.value = await qnaApi.getComments(route.params.id) } catch {}
  }
})

const handleActionClick = () => {
  if (isNew.value || isEditing.value) {
    handleSave()
  } else {
    isEditing.value = true
  }
}

const handleSave = async () => {
  errorMsg.value = ''
  if (!form.title.trim()) { errorMsg.value = '제목을 입력해 주세요.'; return }
  if (!form.content.trim()) { errorMsg.value = '내용을 입력해 주세요.'; return }
  try {
    if (isNew.value) {
      await qnaApi.create({ ...form, createdBy: auth.user?.userId ?? 'SYSTEM' })
      successMsg.value = '게시글이 등록되었습니다.'
      router.push('/qna')
    } else {
      const updated = await qnaApi.update(route.params.id, { ...form, createdBy: auth.user?.userId ?? 'SYSTEM' })
      Object.assign(form, updated)
      isEditing.value = false
      successMsg.value = '게시글이 수정되었습니다.'
    }
  } catch (err) {
    errorMsg.value = err?.response?.data?.message || '저장에 실패했습니다.'
  }
}

const handleDelete = async () => {
  confirmOpen.value = false
  try {
    await qnaApi.delete(route.params.id)
    router.push('/qna')
  } catch (err) {
    errorMsg.value = err?.response?.status === 403 ? '삭제 권한이 없습니다.' : '삭제에 실패했습니다.'
  }
}

const handleCommentSubmit = async () => {
  if (!commentContent.value.trim()) return
  try {
    await qnaApi.createComment(route.params.id, { content: commentContent.value.trim(), createdBy: auth.user?.userId ?? 'SYSTEM' })
    comments.value = await qnaApi.getComments(route.params.id)
    commentContent.value = ''
  } catch { errorMsg.value = '댓글 등록에 실패했습니다.' }
}

const handleCommentDelete = async (commentId) => {
  try {
    await qnaApi.deleteComment(route.params.id, commentId)
    comments.value = await qnaApi.getComments(route.params.id)
  } catch { errorMsg.value = '댓글 삭제에 실패했습니다.' }
}
</script>

// frontend/src/pages/QnaDetailPage.jsx
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import useQna from '../hooks/useQna'
import MainLayout from '../components/common/MainLayout'
import Toast from '../components/common/Toast'
import ConfirmDialog from '../components/common/ConfirmDialog'
import QnaForm from '../components/qna/QnaForm'
import QnaCommentList from '../components/qna/QnaCommentList'
import QnaCommentForm from '../components/qna/QnaCommentForm'
import QnaActionBar from '../components/qna/QnaActionBar'

const EMPTY_FORM = { title: '', content: '' }

export default function QnaDetailPage() {
  const { id }   = useParams()
  const isNew    = id === undefined
  const navigate = useNavigate()
  const { user } = useAuth()
  const { fetchOne, createQna, updateQna, deleteQna, fetchComments, createComment, deleteComment } = useQna()

  const [form, setForm]               = useState(EMPTY_FORM)
  const [comments, setComments]       = useState([])
  const [isEditing, setIsEditing]     = useState(isNew)
  const [confirmOpen, setConfirmOpen] = useState(false)
  const [successMsg, setSuccessMsg]   = useState(null)
  const [errorMsg, setErrorMsg]       = useState(null)

  const isOwner = isNew || (form.createdBy === user?.userId)

  useEffect(() => {
    if (!isNew) {
      fetchOne(id)
        .then(data => setForm(data))
        .catch(() => setErrorMsg('게시글을 불러오지 못했습니다.'))
      fetchComments(id)
        .then(data => setComments(data))
        .catch(() => {})
    }
  }, [id, isNew])

  const handleFormChange = (e) => {
    const { name, value } = e.target
    setForm(prev => ({ ...prev, [name]: value }))
  }

  const handleSave = async () => {
    if (!form.title.trim())   { setErrorMsg('제목을 입력해 주세요.'); return }
    if (!form.content.trim()) { setErrorMsg('내용을 입력해 주세요.'); return }
    try {
      if (isNew) {
        await createQna({ ...form, createdBy: user?.userId ?? 'SYSTEM' })
        setSuccessMsg('게시글이 등록되었습니다.')
        navigate('/qna')
      } else {
        const updated = await updateQna(id, { ...form, createdBy: user?.userId ?? 'SYSTEM' })
        setForm(updated)
        setIsEditing(false)
        setSuccessMsg('게시글이 수정되었습니다.')
      }
    } catch (err) {
      setErrorMsg(err?.response?.data?.message || '저장에 실패했습니다.')
    }
  }

  const handleDelete = async () => {
    try {
      await deleteQna(id)
      navigate('/qna')
    } catch (err) {
      const status = err?.response?.status
      if (status === 403) setErrorMsg('삭제 권한이 없습니다.')
      else setErrorMsg('삭제에 실패했습니다.')
    }
  }

  const handleCommentSubmit = async (content) => {
    try {
      await createComment(id, { content, createdBy: user?.userId ?? 'SYSTEM' })
      const data = await fetchComments(id)
      setComments(data)
    } catch {
      setErrorMsg('댓글 등록에 실패했습니다.')
    }
  }

  const handleCommentDelete = async (commentId) => {
    try {
      await deleteComment(id, commentId)
      const data = await fetchComments(id)
      setComments(data)
    } catch {
      setErrorMsg('댓글 삭제에 실패했습니다.')
    }
  }

  return (
    <MainLayout>
      <Toast message={successMsg} type="success" onClose={() => setSuccessMsg(null)} />
      <Toast message={errorMsg}   type="error"   onClose={() => setErrorMsg(null)} />

      <div className="space-y-4">
        <h1 className="text-xl font-bold text-gray-800">
          {isNew ? 'Q&A 등록' : 'Q&A 상세'}
        </h1>

        <QnaForm
          data={form}
          onChange={handleFormChange}
          readOnly={!isNew && !isEditing}
        />

        {!isNew && (
          <>
            <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
              <h3 className="text-sm font-semibold text-gray-700 mb-3">댓글</h3>
              <QnaCommentList
                comments={comments}
                user={user}
                onDeleteComment={handleCommentDelete}
              />
            </div>
            <QnaCommentForm onSubmit={handleCommentSubmit} />
          </>
        )}
      </div>

      <QnaActionBar
        isNew={isNew}
        isOwner={isOwner}
        onSave={isEditing || isNew ? handleSave : () => setIsEditing(true)}
        onDelete={() => setConfirmOpen(true)}
      />

      {confirmOpen && (
        <ConfirmDialog
          message="게시글을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다."
          onConfirm={() => { setConfirmOpen(false); handleDelete() }}
          onCancel={() => setConfirmOpen(false)}
        />
      )}
    </MainLayout>
  )
}
